AWSTemplateFormatVersion: '2010-09-09'
Description: Environment-aware ALB stack with optional HTTPS and ACM (External DNS)

Parameters:

  EnvironmentName:
    Type: String
    AllowedValues:
      - dev
      - staging
      - prod

  AppName:
    Type: String
    Description: Example Signature-Portal

  DomainName:
    Type: String
    Default: ""
    Description: Optional domain name (required for HTTPS)

  ContainerPort:
    Type: Number
    Default: 3000

  # Passed from parent (root) when used as nested stack
  PublicSubnet1Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 1 (from Network stack)
  PublicSubnet2Id:
    Type: AWS::EC2::Subnet::Id
    Description: Public subnet 2 (from Network stack)
  VpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID (from Network stack)
  ALBSecurityGroupId:
    Type: AWS::EC2::SecurityGroup::Id
    Description: ALB security group (from Network stack)

Conditions:

  IsProd: !Equals [!Ref EnvironmentName, prod]
  HasDomain: !Not [!Equals [!Ref DomainName, ""]]
  CreateHTTPS: !And [!Condition IsProd, !Condition HasDomain]

Resources:

# -------------------------------------------------------
# ACM Certificate (Manual DNS Validation Required)
# -------------------------------------------------------
  Certificate:
    Condition: CreateHTTPS
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Ref DomainName
      SubjectAlternativeNames:
        - !Sub www.${DomainName}
      ValidationMethod: DNS
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-Certificate-${EnvironmentName}
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref AppName

# -------------------------------------------------------
# Application Load Balancer
# -------------------------------------------------------
  ALB:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub ${AppName}-ALB-${EnvironmentName}
      Scheme: internet-facing
      Type: application
      Subnets:
        - !Ref PublicSubnet1Id
        - !Ref PublicSubnet2Id
      SecurityGroups:
        - !Ref ALBSecurityGroupId
      LoadBalancerAttributes:
        - Key: deletion_protection.enabled
          Value: !If [IsProd, true, false]
        - Key: idle_timeout.timeout_seconds
          Value: 60
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-ALB-${EnvironmentName}
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref AppName

# -------------------------------------------------------
# Target Group
# -------------------------------------------------------
  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub ${AppName}-TargetGroup-${EnvironmentName}
      Port: !Ref ContainerPort
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3
      Matcher:
        HttpCode: 200-399
      Tags:
        - Key: Name
          Value: !Sub ${AppName}-TargetGroup-${EnvironmentName}
        - Key: Environment
          Value: !Ref EnvironmentName
        - Key: Application
          Value: !Ref AppName

# -------------------------------------------------------
# HTTP Listener
# -------------------------------------------------------
  HTTPListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 80
      Protocol: HTTP
      DefaultActions:
        - !If
          - CreateHTTPS
          - Type: redirect
            RedirectConfig:
              Protocol: HTTPS
              Port: 443
              StatusCode: HTTP_301
          - Type: forward
            TargetGroupArn: !Ref TargetGroup

# -------------------------------------------------------
# HTTPS Listener (Only in Prod + Domain Provided)
# -------------------------------------------------------
  HTTPSListener:
    Condition: CreateHTTPS
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref ALB
      Port: 443
      Protocol: HTTPS
      SslPolicy: ELBSecurityPolicy-TLS13-1-2-2021-06
      Certificates:
        - CertificateArn: !Ref Certificate
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup

Outputs:

  ALBArn:
    Value: !Ref ALB
    Export:
      Name: !Sub ${AppName}-ALB-${EnvironmentName}-Arn

  ALBDNSName:
    Value: !GetAtt ALB.DNSName
    Export:
      Name: !Sub ${AppName}-ALB-${EnvironmentName}-DNS

  TargetGroupArn:
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${AppName}-TargetGroup-${EnvironmentName}-Arn

  # Export for ECS cross-stack reference (same ARN, name expected by ECS stack)
  TargetGroupArnTg:
    Description: Target group ARN (export name for ECS)
    Value: !Ref TargetGroup
    Export:
      Name: !Sub ${AppName}-tg-${EnvironmentName}
